"""Nullable last_updated

Revision ID: 79d9c460d894
Revises: c97ab6bb188c
Create Date: 2020-05-08 15:08:02.582160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "79d9c460d894"
down_revision = "c97ab6bb188c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sprints", "last_updated", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE sprints SET last_updated='2000-01-01 01:00:00+00' WHERE last_updated IS NULL"
    )
    op.alter_column(
        "sprints", "last_updated", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
