"""Add IssueSnapshots

Revision ID: c855e41ba251
Revises: 99242b3e4f37
Create Date: 2020-04-17 10:42:12.425418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "c855e41ba251"
down_revision = "99242b3e4f37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jira_project_id", sa.Integer(), nullable=True),
        sa.Column("sprint_id", sa.Integer(), nullable=True),
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("story_points", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["jira_project_id"],
            ["jira_projects.id"],
            name=op.f("fk_issue_snapshots_jira_project_id_jira_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["sprint_id"],
            ["sprints.sprint_id"],
            name=op.f("fk_issues_sprint_id_sprints"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issues")),
    )
    op.execute("DELETE FROM sprints")
    op.add_column("sprints", sa.Column("last_updated", sa.DateTime(), nullable=False))
    op.add_column("sprints", sa.Column("state", sa.String(), nullable=False))
    op.add_column("sprints", sa.Column("complete_date", sa.DateTime(), nullable=True))
    op.add_column("sprints", sa.Column("jira_sprint_id", sa.Integer(), nullable=True))
    op.alter_column(
        "sprints", "end_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "sprints", "start_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.create_unique_constraint(
        op.f("uq_sprints_jira_sprint_id"), "sprints", ["jira_sprint_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM issue_snapshots")
    op.execute("DELETE FROM sprints")
    op.drop_constraint(op.f("uq_sprints_jira_sprint_id"), "sprints", type_="unique")
    op.drop_column("sprints", "jira_sprint_id")
    op.drop_column("sprints", "complete_date")
    op.alter_column(
        "sprints", "start_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "sprints", "end_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_column("sprints", "state")
    op.drop_column("sprints", "last_updated")
    op.drop_table("issue_snapshots")
    # ### end Alembic commands ###
