"""Change activities teams sprints relationships

Revision ID: c97ab6bb188c
Revises: c855e41ba251
Create Date: 2020-05-01 10:05:32.568143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c97ab6bb188c"
down_revision = "c855e41ba251"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM issue_snapshots")
    op.execute("DELETE FROM sprints")
    op.drop_constraint(
        "fk_issue_snapshots_jira_project_id_jira_projects",
        "issue_snapshots",
        type_="foreignkey",
    )
    op.drop_column("issue_snapshots", "jira_project_id")
    op.add_column("sprints", sa.Column("activity_id", sa.Integer(), nullable=False))
    op.add_column("sprints", sa.Column("name", sa.String(), nullable=False))
    op.drop_constraint("fk_sprints_team_id_teams", "sprints", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_sprints_activity_id_activities"),
        "sprints",
        "activities",
        ["activity_id"],
        ["activity_id"],
    )
    op.drop_column("sprints", "team_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM issue_snapshots")
    op.execute("DELETE FROM sprints")
    op.add_column(
        "sprints",
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("fk_sprints_activity_id_activities"), "sprints", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_sprints_team_id_teams", "sprints", "teams", ["team_id"], ["team_id"]
    )
    op.drop_column("sprints", "name")
    op.drop_column("sprints", "activity_id")
    op.add_column(
        "issue_snapshots",
        sa.Column("jira_project_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "fk_issue_snapshots_jira_project_id_jira_projects",
        "issue_snapshots",
        "jira_projects",
        ["jira_project_id"],
        ["id"],
    )
    # ### end Alembic commands ###
