"""Add status category status mapping

Revision ID: d500ac904a36
Revises: 79d9c460d894
Create Date: 2020-05-12 18:04:23.028676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d500ac904a36"
down_revision = "79d9c460d894"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "status_category_status_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "status_category",
            sa.Enum("to_do", "in_progress", "done", name="statuscategory"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.activity_id"],
            name=op.f("fk_status_category_status_mappings_activity_id_activities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_status_category_status_mappings")),
        sa.UniqueConstraint(
            "activity_id",
            "status",
            name=op.f("uq_status_category_status_mappings_activity_id"),
        ),
    )
    op.create_index(
        "ix_status_activity_id_null",
        "status_category_status_mappings",
        ["status"],
        unique=True,
        postgresql_where=sa.text("activity_id IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_status_activity_id_null", table_name="status_category_status_mappings"
    )
    op.drop_table("status_category_status_mappings")
    sa.Enum(name="statuscategory").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
